clear all;

pptx    = exportToPPTX('', ...
    'Dimensions',[12 6], ...
    'Title','tuning curves', ...
    'Author','Zahra', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');

% an = 'e200';
an = 'e201';
% an = 'e145';
% individual        day analysis
dys = [55:73, 75];
% dys = [62:67,69:70,72:74,76,81:85];
% dys = [4:7, 9:11];
for dy=dys
    clearvars -except dys an cc dy pptx
    load(fullfile('Y:\sstcre_analysis\fmats', an, 'days', sprintf('%s_day%03d_plane0_Fall.mat',an, dy)), 'dFF', ...
            'Fc3', 'iscell', 'ybinned', 'changeRewLoc', ...
            'forwardvel', 'licks', 'trialnum', 'rewards')              
    
    bin_size = 3;
    track_length = 270;
    gainf = 3/2;
    nbins = track_length/bin_size;
    eps = find(changeRewLoc>0);
    eps = [eps length(changeRewLoc)];
    rewlocs = changeRewLoc(changeRewLoc>0)*(gainf);    
    tuning_curves = {};
    for ep=[1 2 3]
        % per ep    
        eprng = eps(ep):eps(ep+1);
        trn = trialnum(eprng);  
        rew = rewards(eprng)>0.5;
        % opto period
    %     mask = trn>=3 & trn<8;
        % no probes
    %     mask1 = trn>=8;
        strials = ones(1, length(unique(trn)))*NaN; % only get successful trials
        for trial=unique(trn)
        if trial>=3 % trial < 3, probe trial
            if sum(rew(trn==trial)==1)>0 % if reward was found in the trial
                strials(trial)=trial;        
            end
        end
        end
        strials = strials(~isnan(strials));
        mask = ismember(trn, strials);
        
    %     mask = trn<3;
        eprng = eprng(mask);
        if ~isempty(eprng)
        ypos = ybinned(eprng);
        ypos = ceil(ypos*(gainf)); % gain factor for zahra mice
        [time_moving,time_stop] = vr_stop_and_moving_time(ypos);
        ypos_mov = ypos(time_moving);
        for i = 1:nbins    
            time_in_bin{i} = time_moving(ypos_mov >= (i-1)*bin_size & ypos_mov < i*bin_size);
        end 
        
        % make bins via suyash method
    %     pc = putative_pcs{1};
        pc = logical(iscell(:,1));
        rewloc = rewlocs(ep);
        fc3_ep = Fc3(eprng,:);
        moving_cells_activity = fc3_ep(time_moving,:);
        fc3_pc = fc3_ep(:,pc);
%         % mean length of transients
%         tr_len = zeros(1,size(fc3_pc,2));
%         for c=1:size(fc3_pc,2)
%             cell_fc3 = fc3_pc(:,c);
%             diffs = diff(cell_fc3>0);        
%             starts = find(diffs==1);
%             stops = find(diffs==-1);
%             if size(starts,1)>size(stops,1) % to account for parts of transients being cut off from trialnum chunkin
%                 stops(end+1) = size(cell_fc3,1);                
%             end
%             starts_ = starts;
%             if size(starts,1)<size(stops,1)
%                 starts_ = zeros(size(stops,1),1);
%                 starts_(2:end) = starts;
%                 starts_(1) = 0;
%             end       
%             if size(stops,2)==size(starts_,1)
%                 stops = stops';
%             end
%             start_stop = stops-starts_;
%             
%             tr_len(c) = mean(start_stop, 'omitnan');
%         end
%         tr_len = tr_len(tr_len>0); % removes negative lengths for now
        % may want to deal with this later as it it basically because of
        % lingering transients in the beginning and end of time period
        % maybe smaller in 
        cell_activity = zeros(nbins, size(fc3_pc,2));
        for i = 1:size(fc3_pc,2)
            for bin = 1:nbins
                cell_activity(bin,i) = mean(fc3_pc(time_in_bin{bin},i)); 
            end
        end 
        lick = licks(eprng);
        fv = forwardvel(eprng);
        for bin = 1:nbins
            vel(bin) = mean(fv(time_in_bin{bin}));     
            lk(bin) = mean(lick(time_in_bin{bin}));     
        end
        cell_activity(isnan(cell_activity)) = 0;
        
        if ep == 1 % sort by ep 1
    %         % sort by max value
    %         peak = zeros(1, size(cell_activity,2));
    %         for c=1:size(cell_activity,2)
    %             f = cell_activity(:,c);
    %             if sum(f)>0
    %                 [peakval,peakbin] = max(f);
    %                 peak(c) = peakbin;
    %             else
    %                 peak(c) = 1;
    %             end
    %         end
            % sort by median - ed's code
            com = calc_COM_EH(cell_activity',bin_size);
            
    %         [~,sorted_idx] = sort(peak);
            [~,sorted_idx] = sort(com);
        end
        end
        tuning_curves{ep} = cell_activity;        
        
    end

    comparisons = {[1 2], [1 3], [2 3]};
    for i=1:length(comparisons)
        comparison = comparisons{i};
        [p,h,stat] = do_tuning_curve_ranksum_test(tuning_curves{comparison(1)}', ...
            tuning_curves{comparison(2)}');
        pvals(i) = p;
        disp(p)
    end
    slideId = pptx.addSlide();
    fprintf('Added slide %d\n',slideId);
    fig = figure('Renderer', 'painters', 'Position', [10 10 1050 800]);
    for ep=[1 2 3]        
        subplot(1,3,ep)
        imagesc(normalize(tuning_curves{ep}(:,sorted_idx),1)'); 
        colormap jet 
        xticks([0:3:90])
        xticklabels([0:9:270])
        %     subplot(2,1,2)
        %     plot(vel, 'k');
        %     yyaxis right
        %     plot(lk, 'r'); ylim([0 0.5])
        %     hold on 
        %     rectangle('Position',[(rewloc-5)/3 0 10/3 max(lk)+1], ... % just picked max for visualization
        %           'FaceColor',[0 .5 .5 0.3])
        %     xticks([0:90])
        %     xticklabels([0:3:270])
        title(sprintf('epoch %i', ep))
    end
    
    sgtitle(sprintf(['animal %s, day %i \n ' ...
            'ep1 vs ep2 = %d \n ep1 vs ep3 = %d \n ep2 vs ep3 = %d'], an, dy, pvals))
    pptx.addPicture(fig);
    pptx.addTextbox(sprintf('%s_day%i',an,dy));
    pptx.addNote(sprintf('Notes data: slide number %d',slideId));
    
    savefig(fullfile('Y:\sstcre_analysis\figures',sprintf('%s_day%i_tuning_curves_w_ranksum.fig',an,dy)))
    close(fig)
end
% save ppt
fl = pptx.save(fullfile('Y:\sstcre_analysis',sprintf('%s_tuning_curves_w_ranksum',an)));