%  Reliability was defined as the pairwise Pearson correlation between the activity on each trial
% https://www.nature.com/articles/s41593-022-01050-4
% zahra's analysis for opto
% goal is to see population level differences when you inhibit vips
clear all;

an = 'e218';
% individual day analysis 
dys = [20:46];
src = 'X:\vipcre'; % folder where fall is
savedst = 'C:\Users\Han\Box\neuro_phd_stuff\han_2023\figure_data'; % where to save ppt of figures
pptx    = exportToPPTX('', ... % make new file
    'Dimensions',[12 6], ...
    'Title','correlation', ...
    'Author','zahra', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');

for dy=dys % for loop per day
    clearvars -except dys an cc dy src savedst pptx
    pth = dir(fullfile(src, an, string(dy), '**\*Fall.mat'));
    % load vars
    load(fullfile(pth.folder,pth.name))
    
    eps = find(changeRewLoc>0);
    eps = [eps length(changeRewLoc)]; % make epoch struct
    track_length = 180/VR.scalingFACTOR;
    ybinned = ybinned/VR.scalingFACTOR;
    rewlocs = changeRewLoc(changeRewLoc>0)/VR.scalingFACTOR;
    rewsize = VR.settings.rewardZone/VR.scalingFACTOR;
    if exist('trialnumall','var') == 1
    else
    trialnumall = trialnum+1;
    for ep=1:length(eps)-1 % make big trialnum variable with all the trials sequentially
        eprng = eps(ep):eps(ep+1)-1;
        trialnumall_ep = trialnumall(eprng);        
        if ep>1
            lasttr = max(unique(trialnumall(eps(ep-1):eps(ep)-1))); % last trial from prev ep
            trialnumall_ep = trialnumall_ep+lasttr;
        end
        trialnumall(eprng) = trialnumall_ep;
    end
    disp('************** saving big trialnum variable to fall.mat **************')
    save(fullfile(pth.folder,pth.name), 'trialnumall', '-append')
    end
    % only correlate pcs, TODO: make into function
    pcs = reshape(cell2mat(putative_pcs), [length(putative_pcs{1}), length(putative_pcs)]);
    pc = logical(iscell(:,1));
    [~,bordercells] = remove_border_cells_all_cells(stat, Fc3);        
    bordercells_pc = bordercells(pc); % mask border cells
    fc3_pc = Fc3(:,pc); % only iscell
    fc3_pc = fc3_pc(:,~bordercells_pc); % remove border cells
    fc3_pc = fc3_pc(:, any(pcs,2)); % apply place cell filter, if a cell is considered a place cell in any ep!!
    % activity binning
    corrmat = zeros(max(trialnumall),size(fc3_pc,2));
    for i=1:size(fc3_pc,2)
        corrmat(:,i) = accumarray(trialnumall',fc3_pc(:,i),[],@mean); % bins by trialnum
    end
    
    corrmatall = corr(corrmat', 'rows', 'complete');
    %%
    fig = figure('Renderer', 'painters');
    slideId = pptx.addSlide();
    fprintf('Added slide %d\n',slideId);
    imagesc(corrmatall); colormap parula
    hold on;
    probes = unique(trialnumall(trialnum<3));
    for pr=probes % mark probes
        xline(pr, 'w--')
        yline(pr, 'w--')
    end
    xticks(0:10:max(unique(trialnumall))-1)
    xticklabels(0:10:max(unique(trialnumall)))
    yticks(0:10:max(unique(trialnumall))-1)
    yticklabels(0:10:max(unique(trialnumall)))
    xlabel('Trial-by-trial Pearson correlation of Fc3')
    sgtitle(sprintf('animal: %s, day %i', an, dy))
    colorbar;
    pptx.addPicture(fig);
    close(fig)
end
% save ppt
fl = pptx.save(fullfile(savedst,sprintf('%s_trialbytrial_pearson_corr',an)));