% Zahra
% day to day analysis for rewards in the dark using suite2p ROIS
% SST cre experiment
% want to plot and see if there is any activity of cells during CS/US
clear all
dys = [8:27,29:35];
mouse_name = "e200";
cnt = 1; %counter for days

for dy=dys
    src = "Y:\sstcre_imaging";
    fmatfl = dir(fullfile(src, mouse_name, sprintf('%i',dy), '**\Fall.mat'));
    load(fullfile(fmatfl.folder, fmatfl.name))
    %%
    % dff = redo_dFF(F, 31.25, 20, Fneu);
    % save('Y:\sstcre_imaging\e200\20\230315_ZD_000_000\suite2p\plane0\Fall.mat', 'dFF', '-append')
    dFF = dFF';
    skews = cell2mat(cellfun(@(x) x.skew, stat, 'UniformOutput', false));
    dFF = dFF(logical(iscell(:,1)),:);   
    range=10;
    bin=0.1;
    rewardsonly=rewards>=1;
    cs=rewards==0.5;
    % F = F(logical(iscell(:,1)),:);
    % runs for all cells
    [binnedPerireward,allbins,rewdFF] = perirewardbinnedactivity(dFF',cs,timedFF,range,bin); %rewardsonly if mapping to reward
    [vbinnedPerireward,vallbins,vrewdFF] = perirewardbinnedactivity(forwardvel',cs,timedFF,range,bin); %rewardsonly if mapping to reward
    [lbinnedPerireward,~,~] = perirewardbinnedactivity(licks',cs,timedFF,range,bin); %rewardsonly if mapping to reward
    perirew{cnt} = binnedPerireward; % individual cells
    vperirew{cnt} = vbinnedPerireward;
    lperirew{cnt} = lbinnedPerireward;    
    cnt = cnt+1;
end
%%
%plot summary figure
pptx    = exportToPPTX('', ...
    'Dimensions',[12 6], ...
    'Title','pyramidal cell dark reward analysis', ...
    'Author','Zahra', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');

slideId = pptx.addSlide();
fprintf('Added slide %d\n',slideId);
fig = figure('Renderer', 'painters');
vmat = reshape(cell2mat(vperirew), [200,length(vperirew)]);
lmat = reshape(cell2mat(lperirew), [200,length(lperirew)]);
fmat = reshape(cell2mat(cellfun(@(x) mean(x), perirew, 'UniformOutput',false)), [200,length(lperirew)]);
ax1 = subplot(3,1,1);
imagesc(vmat')
xticks([0:20:200])
xticklabels([-10:2:10])
colormap(ax1,gray)
title('binned velocity')
ylabel('days')
ax2 = subplot(3,1,2);
imagesc(lmat')
xticks([0:20:200])
xticklabels([-10:2:10])
colormap(ax2,autumn)
title('binned licks')
ylabel('days')
ax3 = subplot(3,1,3);
imagesc(normalize(fmat',2))
xticks([0:20:200])
xticklabels([-10:2:10])
colormap(ax3,jet)
title('binned mean')
ylabel('days')
sgtitle('cs triggered averages')
pptx.addPicture(fig);
pptx.addTextbox(sprintf('%s, mean activity across days',mouse_name));
pptx.addNote(sprintf('slide number %d',slideId));
% per day plots
close all;
for i=1:length(perirew)        
    peak = zeros(1,size(perirew{i},1));
    % sort by max val
    for c=1:size(perirew{i},1)
    f = perirew{i}(c,:);
    if sum(f)>0
        [peakval,peakbin] = max(f);
        peak(c) = peakbin;
    else
        peak(c) = 1;
    end
    end
    [~,sorted_idx] = sort(peak);
    com = calc_COM_EH(perirew{i},1);
    [~,sorted_idx] = sort(com);    
    slideId = pptx.addSlide();
    fprintf('Added slide %d\n',slideId);
    fig = figure('Renderer', 'painters');
    imagesc(normalize(perirew{i}(sorted_idx,:),2)); hold on
    xline(101,'k--', {'CS'}, 'LineWidth', 3)
    colormap jet
    title(sprintf('day %i of rr', dys(i)))
    pptx.addPicture(fig);
    close(fig)
end
% save ppt
fl = pptx.save(fullfile('Y:\sstcre_analysis',sprintf('%s_randomreward',mouse_name)));

% 
% ax4 = subplot(2,1,1);
% imagesc(vmat')
% xticks([0:20:200])
% xticklabels([-10:2:10])
% colormap(ax4,gray)
% title('binned velocity')
% ylabel('days')
% ax5 = subplot(2,1,2);
% imagesc(normalize(fmat',2))
% xline(100, 'k--', 'CS', 'LineWidth',3)
% xticks([0:20:200])
% xticklabels([-10:2:10])
% colormap(ax5,jet)
% title('binned average dff')
% ylabel('days')

%%
% per cell
% pick a random cell
% c = randi([30 50],1,1);
% vmat = reshape(cell2mat(vperirew), [200,length(vperirew)]);
% lmat = reshape(cell2mat(lperirew), [200,length(lperirew)]);
% fmat = reshape(cell2mat(cellfun(@(x) x(c,:), perirew, 'UniformOutput',false)), [200,length(lperirew)]);
% ax1 = subplot(3,1,1);
% imagesc(vmat')
% xticks([0:20:200])
% xticklabels([-10:2:10])
% colormap(ax1,gray)
% title('binned velocity')
% ylabel('days')
% ax2 = subplot(3,1,2);
% imagesc(lmat')
% xticks([0:20:200])
% xticklabels([-10:2:10])
% colormap(ax2,autumn)
% title('binned licks')
% ylabel('days')
% ax3 = subplot(3,1,3);
% imagesc(normalize(fmat',2))
% xticks([0:20:200])
% xticklabels([-10:2:10])
% colormap(ax3,jet)
% title('binned average dff')
% ylabel('days')
% sgtitle('cs triggered averages')
%%
% find cells corr with velocity
corrs = {};
for day=1:length(perirew)
    f = perirew{day};
    corr_ = {}; 
    for c=1:size(f,1)
        fc = f(c,:);
        vc = vperirew{day};
        corr = corrcoef(fc,vc);
        corr_{c} = corr(2,1); % take diagonal values
    end
    corrs{day} = corr_;    
end
%%
% early days vs late days or all days
avcorr = {};
for day=1:length(perirew)
    poscorr = cell2mat(corrs{day})>0.7;
    negcorr = cell2mat(corrs{day})<-0.7;
    notcorr = (cell2mat(corrs{day})>-0.5 & cell2mat(corrs{day})<0.5);
    ccorr = perirew{day}(notcorr,:);
    cpos = perirew{day}(poscorr,:);
    cneg = perirew{day}(negcorr,:);
%     figure;
%     ax1 = subplot(2,1,1);
%     imagesc(vmat(:,day)')
%     xticks([0:20:200])
%     xticklabels([-10:2:10])
%     colormap(ax1,gray)
%     title('binned velocity')
%     ylabel('days')
%     ax2 = subplot(2,1,2);
%     imagesc(normalize(ccorr,2))
%     colormap(ax2,jet)
%     title('binned dff')
%     ylabel('cells')
%     sgtitle(sprintf('day %i of RR', day))
    avcorr{day} = mean(ccorr, 1); % average of uncorrelated cells
end

avcorr = reshape(cell2mat(avcorr), [200,length(avcorr)]);

% plot average of non correlated cells
ax1 = subplot(3,1,1);
imagesc(vmat')
xticks([0:20:200])
xticklabels([-10:2:10])
colormap(ax1,gray)
title('binned velocity')
ylabel('days')
ax2 = subplot(3,1,2);
imagesc(lmat')
xticks([0:20:200])
xticklabels([-10:2:10])
colormap(ax2,autumn)
title('binned licks')
ylabel('days')
ax3 = subplot(3,1,3);
imagesc(normalize(avcorr',2))
xticks([0:20:200])
xticklabels([-10:2:10])
colormap(ax3,jet)
title('binned average dff')
ylabel('days')
sgtitle('cs triggered averages')