% zahra adaptation of gm's code
% sst individual cell profiles
clear all; close all
an = 'e136';
dy = 6;
load(fullfile("Y:\analysis\fmats", sprintf("%s", an), sprintf("%s_day%03d_plane0_Fall.mat", an, dy)));
pln0 = load(fullfile("Y:\analysis\fmats", sprintf("%s", an), sprintf("%s_day%03d_plane0_Fall.mat", an, dy)));
pln1 = load(fullfile("Y:\analysis\fmats", sprintf("%s", an), sprintf("%s_day%03d_plane1_Fall.mat", an, dy)));
pln2 = load(fullfile("Y:\analysis\fmats", sprintf("%s", an), sprintf("%s_day%03d_plane2_Fall.mat", an, dy)));
plns = {};
plns{1} = pln0; plns{2} = pln1; plns{3} = pln2;
planes = 3;
bin_size = 0.2; %s
range = 10; %s
eps = find(changeRewLoc>0);
eps = [eps length(changeRewLoc)];
track_length = 180; %cm; TODO: import from VR instead
nbins = track_length/bin_size;
rewlocs = changeRewLoc(changeRewLoc>0);
rewsize = 10; %cm
grayColor = [.7 .7 .7];
savedst = 'C:\Users\Han\Box\neuro_phd_stuff\han_2023-\figure_data\sst';
%%
% params to export to ppt
pptx    = exportToPPTX('', ...
    'Dimensions',[12 6], ...
    'Title','cell profiles', ...
    'Author','Zahra', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');

dFF_all_planes = {pln0.dFF_iscell, pln1.dFF_iscell, pln2.dFF_iscell};

for plane=1:planes
    dff = dFF_all_planes{plane}';
    [binnedPerireward,allbins,rewdFF,normmeanrewdFF] = perirewardbinnedactivity(dff,rewards,timedFF, ...
        range,bin_size);
    [binnedvel,~,rewvel] = perirewardbinnedvelocity(forwardvel,rewards,timedFF, ...
        range,bin_size);

    fig = figure('Renderer', 'painters', 'WindowState', 'maximized');
    slideId = pptx.addSlide();
    fprintf('Added slide %d\n',slideId);
    for cll=1:size(dff,2)+1
        subplot(ceil(sqrt(size(dff,2))),ceil(sqrt(size(dff,2))),cll)
        for rewind = 1:size(rewdFF,3)
            try % to allow for velocity plot
                plot(rewdFF(:,cll,rewind), 'Color', [.7 .7 .7]); hold on % plot each trial
            catch
            end
        end
        try
            plot(binnedPerireward(cll,:), 'k', 'LineWidth', 1.5); hold on % mean trial plot each cell
        catch
        end
        xline(median(1:size(allbins,2)), 'b--', 'LineWidth', 1.5) % mark reward
        xticks(0:25:size(allbins,2))
        xticklabels(-range:5:range)
        xlabel('Time (s) from Reward')
        if cll==size(dff,2)+1
            for rewind = 1:size(rewvel,2)
                plot(rewvel(:,rewind), 'k'); hold on % plot each trial
            end
            ylabel('Velocity (cm/s)')
            xline(median(1:size(allbins,2)), 'b--', 'LineWidth', 1.5) % mark reward
            xticks(0:25:size(allbins,2))
            xticklabels(-range:5:range)
        end
    end

    sgtitle(sprintf('All successful trials, plane %i', plane))
    pptx.addPicture(fig);
    export_fig(fullfile(savedst, sprintf('%s_successful_trials_cell_profiles_peri_reward_plane%i', an, plane)), '-svg')
    close(fig)
end
% save ppt
fl = pptx.save(fullfile(savedst,sprintf('%s_successful_trial_cell_profiles_day%i',an,dy)));
